require "lib/base"
require 'fileutils'

task :default => [:build]

desc "convert all markdown to html"
task :build do
  ruby %{buildDoc.rb}
end

desc "build Windows native file"
task :build_exe do
  def buildExe
    Dir["*.rb"].each do |file|
      file_name = File.basename(file)[0..-4]
      system("dir & exerb #{file_name}.rb")
      system("dir & mkexy #{file_name}.rb")
      system("dir & exerb #{file_name}.exy")
      system("dir & del #{file_name}.exy")
    end
  end

  if platform == 'win'
    buildExe
    
    Dir.chdir('search')
    
    setup_file = %q{
      from distutils.core import setup
      import py2exe

      includes = ["encodings", "encodings.*"]
      options = {"py2exe":
                  {   "compressed": 1,
                      "optimize": 2,
                      "includes": includes,
                      "bundle_files": 1
                  }
                }
      setup(   
          version = "0.0.1",
          description = "search",
          name = "search",
          options = options,
          zipfile=None,
          console=["search.py"]
          # console=[{"script": "search.py", "icon_resources": [(1, "search.ico")] }] 
          )
      }.gsub(/^\s*/,'')
    
    output = File.open('setup.py', 'w')
    output.puts setup_file
    output.close
    
    system("python setup.py py2exe")
    FileUtils.mv('dist/search.exe', 'search.exe')
    FileUtils.rm_rf('build')
    FileUtils.rm_rf('dist')
    FileUtils.rm_rf('setup.py')

  else
    puts 'must run in MS-Windows'
  end
end


desc "clean all html files in _output"
task :clean do
  Dir["**/_output/*.html"].each do |file|
    File.delete(file)
  end
end
